import os
import pandas as pd
import glob
import re

# --- CONFIGURATION ---
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CSV_DIR = os.path.join(BASE_DIR, 'content', 'source_csvs')
OUTPUT_DIR = os.path.join(BASE_DIR, 'src', 'data')

def clean_text(text):
    if pd.isna(text): return ""
    return str(text).strip().replace('"', "'")

def generate_id(text):
    if pd.isna(text): return "unknown"
    return re.sub(r'[^a-z0-9]', '', str(text).lower())[:20]

def process_scenarios():
    print(f"🔍 Scanning for scenario CSVs in {CSV_DIR}...")
    # Find all files ending in scenarios.csv
    files = glob.glob(os.path.join(CSV_DIR, "*_scenarios.csv"))
    
    if not files:
        print("⚠️  No scenario CSVs found. Skipping.")
        return

    all_scenarios = []
    
    for file in files:
        filename = os.path.basename(file)
        # Use filename as the ID if not in CSV (e.g. 'bank_scenarios.csv' -> 'bank')
        default_id = filename.replace('_scenarios.csv', '').replace('.csv', '')
        
        try:
            df = pd.read_csv(file)
            print(f"   -> Processing {filename} ({len(df)} rows)")
            
            # Normalize columns
            df.columns = [c.lower().strip() for c in df.columns]
            
            # Create scenario object
            scenario = {
                "id": default_id,
                "title": default_id.replace('_', ' ').title(),
                "difficulty": "Intermediate", # Default
                "description": f"Practice listening in a {default_id} environment.",
                "items": []
            }
            
            # Map CSV rows to items
            # Looks for columns like 'speaker', 'text', 'difficulty'
            for _, row in df.iterrows():
                item = {
                    "id": generate_id(row.get('text', '')),
                    "speaker": row.get('speaker', 'Unknown'),
                    "text": clean_text(row.get('text', row.get('sentence', ''))),
                    "difficulty": row.get('difficulty', 'easy')
                }
                scenario['items'].append(item)
                
            all_scenarios.append(scenario)
            
        except Exception as e:
            print(f"❌ Error reading {filename}: {e}")

    # Write to TypeScript
    output_path = os.path.join(OUTPUT_DIR, 'scenarios.ts')
    with open(output_path, 'w') as f:
        f.write("// Auto-generated by scripts/ingest_content.py\n")
        f.write("import { Scenario } from '../types';\n\n")
        f.write("export const scenarios: Scenario[] = ")
        f.write(str(all_scenarios).replace("'", '"')) # JSON-like formatting
        f.write(";\n")
    
    print(f"✅ Generated {output_path} with {len(all_scenarios)} scenarios.")

def main():
    if not os.path.exists(CSV_DIR):
        print(f"❌ Error: CSV directory not found at {CSV_DIR}")
        return

    process_scenarios()
    # Add functions for words/stories here following the same pattern if needed

if __name__ == "__main__":
    main()