// Auto-generated by scripts/ingest_content.py
import { Scenario } from '../types/activity';

export const scenarios: Scenario[] = [
  {
    "id": "hearingrehabprojectscenarios",
    "title": "Hearing Rehab Project - Scenarios",
    "difficulty": "easy",
    "description": "Practice listening in a Hearing Rehab Project - Scenarios environment.",
    "items": [
      {
        "id": "whatcanigetforyou",
        "speaker": "female_barista",
        "text": "What can I get for you?",
        "difficulty": "easy"
      },
      {
        "id": "thatllbefourdollarsa",
        "speaker": "male_barista",
        "text": "That'll be four dollars and fifty cents.",
        "difficulty": "easy"
      },
      {
        "id": "sothatsonelargecoffe",
        "speaker": "female_barista",
        "text": "So that's one large coffee for you.",
        "difficulty": "easy"
      },
      {
        "id": "whatsizewouldyoulike",
        "speaker": "male_barista",
        "text": "What size would you like? We have small, medium, and large.",
        "difficulty": "easy"
      },
      {
        "id": "formilkwehavewholemi",
        "speaker": "female_barista",
        "text": "For milk, we have whole milk and oat milk available today.",
        "difficulty": "easy"
      },
      {
        "id": "wouldyoulikethatforh",
        "speaker": "male_barista",
        "text": "Would you like that for here or to go?",
        "difficulty": "easy"
      },
      {
        "id": "alrightsothatsalarge",
        "speaker": "female_barista",
        "text": "Alright, so that's a large iced coffee with oat milk and an extra shot.",
        "difficulty": "easy"
      },
      {
        "id": "yourtotalcomestosixd",
        "speaker": "male_barista",
        "text": "Your total comes to six dollars and forty-seven cents with tax.",
        "difficulty": "easy"
      },
      {
        "id": "itllbeaboutfiveminut",
        "speaker": "female_barista",
        "text": "It'll be about five minutes for that because we're making a fresh batch right now.",
        "difficulty": "easy"
      }
    ],
    "tier": "free"
  },
  {
    "id": "coffeeshop",
    "title": "Coffee Shop",
    "difficulty": "easy",
    "description": "Practice listening in a coffee shop environment.",
    "items": [
      {
        "id": "whatcanigetforyou",
        "speaker": "female_barista",
        "text": "What can I get for you?",
        "difficulty": "easy"
      },
      {
        "id": "thatllbefourdollarsa",
        "speaker": "male_barista",
        "text": "That'll be four dollars and fifty cents.",
        "difficulty": "easy"
      },
      {
        "id": "sothatsonelargecoffe",
        "speaker": "female_barista",
        "text": "So that's one large coffee for you.",
        "difficulty": "easy"
      },
      {
        "id": "whatsizewouldyoulike",
        "speaker": "male_barista",
        "text": "What size would you like? We have small, medium, and large.",
        "difficulty": "easy"
      },
      {
        "id": "formilkwehavewholemi",
        "speaker": "female_barista",
        "text": "For milk, we have whole milk and oat milk available today.",
        "difficulty": "easy"
      },
      {
        "id": "wouldyoulikethatforh",
        "speaker": "male_barista",
        "text": "Would you like that for here or to go?",
        "difficulty": "easy"
      },
      {
        "id": "alrightsothatsalarge",
        "speaker": "female_barista",
        "text": "Alright, so that's a large iced coffee with oat milk and an extra shot.",
        "difficulty": "easy"
      },
      {
        "id": "yourtotalcomestosixd",
        "speaker": "male_barista",
        "text": "Your total comes to six dollars and forty-seven cents with tax.",
        "difficulty": "easy"
      },
      {
        "id": "itllbeaboutfiveminut",
        "speaker": "female_barista",
        "text": "It'll be about five minutes for that because we're making a fresh batch right now.",
        "difficulty": "easy"
      }
    ],
    "tier": "free"
  }
];
